import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const competitionDirectory = path.join(root, "data", "competitions");
const logDirectories = [
  path.join(root, "data", "logs"),
  path.join(root, "reference", "1st-xrc-29", "cache"),
];
const outputFile = path.join(root, "migrations", "0002_seed.sql");

function sqlText(value) {
  return `CAST(X'${Buffer.from(value, "utf8").toString("hex")}' AS TEXT)`;
}

function utf8Chunks(value, maximumBytes = 40_000) {
  const chunks = [];
  let chunk = "";
  let bytes = 0;
  for (const character of value) {
    const characterBytes = Buffer.byteLength(character, "utf8");
    if (bytes + characterBytes > maximumBytes && chunk) {
      chunks.push(chunk);
      chunk = "";
      bytes = 0;
    }
    chunk += character;
    bytes += characterBytes;
  }
  if (chunk) chunks.push(chunk);
  return chunks;
}

function appendDocument(statements, table, id, text, insertStatement) {
  statements.push(insertStatement);
  let expectedBytes = 0;
  for (const chunk of utf8Chunks(text)) {
    statements.push(
      `UPDATE ${table} SET document = document || ${sqlText(chunk)} WHERE id = ${sqlText(id)} AND length(CAST(document AS BLOB)) = ${expectedBytes};`,
    );
    expectedBytes += Buffer.byteLength(chunk, "utf8");
  }
}

function readJson(file) {
  const text = fs.readFileSync(file, "utf8");
  return { text: `${JSON.stringify(JSON.parse(text))}\n`, value: JSON.parse(text) };
}

const competitions = fs.readdirSync(competitionDirectory)
  .filter((file) => file.endsWith(".json"))
  .sort()
  .map((file) => readJson(path.join(competitionDirectory, file)));
const requiredLogIds = [...new Set(competitions.flatMap(({ value }) => value.matches.map((match) => match.tenhouLogId)))].sort();
const now = new Date().toISOString();
const statements = [
  "-- Generated by npm run cf:seed:build. Existing cloud data is never overwritten.",
];

for (const { text, value } of competitions) {
  appendDocument(
    statements,
    "competitions",
    value.id,
    text,
    `INSERT INTO competitions (id, document, version, created_at, updated_at) VALUES (${sqlText(value.id)}, '', 1, ${sqlText(now)}, ${sqlText(now)}) ON CONFLICT(id) DO NOTHING;`,
  );
}

for (const logId of requiredLogIds) {
  const file = logDirectories.map((directory) => path.join(directory, `${logId}.json`)).find((candidate) => fs.existsSync(candidate));
  if (!file) throw new Error(`缺少牌谱缓存：${logId}`);
  const { text } = readJson(file);
  appendDocument(
    statements,
    "logs",
    logId,
    text,
    `INSERT INTO logs (id, document, created_at) VALUES (${sqlText(logId)}, '', ${sqlText(now)}) ON CONFLICT(id) DO NOTHING;`,
  );
}

fs.writeFileSync(outputFile, `${statements.join("\n")}\n`);
console.log(`已生成 ${path.relative(root, outputFile)}：${competitions.length} 个比赛，${requiredLogIds.length} 份牌谱`);
